### ISSUE TITLE
JS01 제작 - 함수와 배열

### ISSUE THREAD

**Issue by cos18** [42js/js_piscine#2]
여러가지 함수와 배열과 관련된 JS문법을 배우는 문제들을 JS01에 넣을 예정입니다.

- [ ] 표현식과 선언문의 차이
- [ ] 화살표함수
- [ ] 배열에서의 for문
- [ ] 배열메소드 (map, foreach, ...)
- [ ] Date 관련 프로그램 제작
- [ ] 외부 모듈(패키지) import (jest)

**Comment by YUJO42** [comment]
ES6에서 도입 된 ```Set()```도 함께 다루면 좋을거 같습니다!

**Comment by cos18** [comment]
해당 이슈는 20년에 작성된 이슈이며, 현재(21년) 새로운 버젼으로 개선중입니다.
