### ISSUE TITLE
[BE00] - EX06 Express로 본격적인 프로젝트 시작하기!

### ISSUE THREAD

**Issue by JaeSeoKim** [42js/js_piscine#21]
문제 내용
---

Express를 이용한 프로젝트 생성에 대해서 학습 할 수 있도록 Subject를 구성 중.

**Comment by JaeSeoKim** [comment]
@Two-Jay, @srngch 님 한번 문제 작성을 해보았는데 어떤지 확인해보고 리뷰 부탁 드릴께요!

66ec2f6

**Comment by srngch** [comment]
문제 확인했습니다! npm 명령어 부분을 잘 정리해주셔서 subject 앞쪽 Instructions에 일괄적으로 제시해도 좋을 것 같아요.

**Comment by JaeSeoKim** [comment]
@ExtraMortals, @srngch님 의견: 문제를 분리하여 난이도를 조절하자.

**Comment by JaeSeoKim** [comment]
@Two-Jay 님 의견: `Ex06`정도의 문제 번호로 변경하자

**Comment by JaeSeoKim** [comment]
@Two-Jay 님 의견: `Response` 에 대한 부분을 Success, Error 를 구분하지 않고 `Code` 로 분리하자.

**Comment by JaeSeoKim** [comment]
@Two-Jay 님 의견을 통해 ex03 -> ex06으로 변경 하겠습니다!

이번주 내로 문제와 제목을 일부 변경하여서 다시 리뷰 요청 하겠습니다.!
