### ISSUE TITLE
[BE00] - EX03 Express 열차 노선도 만들기!

### ISSUE THREAD

**Issue by Two-Jay** [42js/js_piscine#26]
키워드 : Express, Router

주제 : 자유

- 기본적인 익스프레스 활용 첫 문제입니다.
- 최소 2개 이상의 url 에 대한 라우팅 지원이 있어야 합니다.

**Comment by JaeSeoKim** [comment]
[서울교통공사 노선별 지하철역 정보](http://data.seoul.go.kr/dataList/OA-15442/S/1/datasetView.do) 를 활용하여 Router에 들어온 요청을 분석하여 해당 지하철 역 정보를 출력 하는 문제를 만들려고 함.!
