### ISSUE TITLE
JS05(FE02) 초안

### ISSUE THREAD

**Issue by cos18** [42js/js_piscine#34]
늦게 올려 죄송합니다. 해당 내용 확인하시고 의견 남겨주세요! @hochan222 @WONILLISM @MichelleJin12 

## Excersise 00 My notion profile

Notion API를 통해 본인 계정의 유저 목록을 알려주는 서비스를 만드세요.
- 처음 접속시 노션 api 키를 사용자에게 입력받는 입력 폼이 있어야 합니다.
- 입력 받은 키를 기준으로 유저를 "모두" 조회해야 합니다.

## Excersise 01 My notion pages

Notion API를 통해 조회 가능한 글들을 모두 보여주는 서비스를 만드세요.
- ex00의 코드를 활용해도 좋습니다.
- 처음 접속시 노션 api 키를 사용자에게 입력받는 입력 폼이 있어야 합니다.
- 입력 받은 키를 기준으로 조회 가능한 글을 첫 화면에 "모두" 보여줘야 합니다.
> https://developers.notion.com/docs/getting-started

## Excersise 02 Pagination 101

ex01에서 만든 서비스를 바탕으로 글 조회시 pagination을 넣으세요.
> https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Pagination

## Excersise 03 My custom database
(작성중)

**Comment by MichelleJin12** [comment]
좋은 것 같습니다!!
