### ISSUE TITLE
JS02 제작 - 객체

### ISSUE THREAD

**Issue by cos18** [42js/js_piscine#8]
객체를 연습하는 문제들을 JS02에 넣을 예정입니다.

- [ ] 객체 기본 함수
- [ ] 객체 구조분해 (destructuring)
- [ ] JSON.stringify 구현

**Comment by YUJO42** [comment]
객체 부분이면 ```Map()```에 대한 내용도 추가로 들어가면 좋을거 같습니다!

**Comment by cos18** [comment]
해당 이슈는 20년에 작성된 이슈이며, 현재(21년) 새로운 버젼으로 개선중입니다.
